### PR TITLE
Add italian translation

### PR DESCRIPTION
**Pull request by emanuelenardi**

### CODE REVIEW

**Comment by dizballanze** [comment]
Hi Emanuele,
Thanks for the contribution!
There are some [linter warnings](https://github.com/dizballanze/m00dbot/pull/8/checks?check_run_id=2232093196) about too long lines. Please fix them and I'll be ready to merge this patch and deploy the new version.

**Comment by emanuelenardi** [comment]
Now the linting problems should be solved

**Comment by dizballanze** [comment]
New version is deployed

**Comment by emanuelenardi** [comment]
Something isn't right

image

**Comment by dizballanze** [comment]
Fixed

**Pull request merged**
